# PiVoxel standalone server

services:
  server:
    build:
      context: https://codeberg.org/Pivok/PiVoxel.git#5bed85d21c5e55037cb058ee4c72921966b646ad
      dockerfile_inline: |
        FROM alpine:3.24
        RUN apk add zig --repository=https://dl-cdn.alpinelinux.org/alpine/v3.24/community
        WORKDIR /app
        COPY . .
        RUN zig build server -Doptimize=ReleaseSafe
        EXPOSE 2137
        CMD ["./zig-out/bin/pivoxel-server"]
    container_name: pivoxel-server
    ports:
      - "2137:2137/udp"
